apiVersion: v1
kind: Service
metadata:
  name: wisecow-service
  namespace: wisecow
spec:
  selector:
    app: wisecow
  ports:
    - protocol: TCP
      port: 80        # expose standard HTTP to the ingress controller
      targetPort: 4499
  type: ClusterIP
